[build]
rustflags = ["-C", "target-cpu=native"]

[install]
default-features = true

# Configuraci√≥n para WASM
[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=--no-entry",
    "-C", "opt-level=z"
]
